apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforma-monitorizare
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platforma-monitorizare
  template:
    metadata:
      labels:
        app: platforma-monitorizare
    spec:
      containers:
      - name: monitoring
        image: ionsar/sysmonitoring:latest
        env:
        - name: INTERVAL_LOG
          value: "5"
        volumeMounts:
        - name: sysmonitor-volume
          mountPath: /sysmonitor
      - name: backup
        image: ionsar/sysbackup:latest
        env:
        - name: INTERVAL_BACKUP
          value: "5"
        - name: DIR_BACKUP
          value: "/sysmonitor/backup"
        volumeMounts:
        - name: sysmonitor-volume
          mountPath: /sysmonitor
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: sysmonitor-volume
          mountPath: /usr/share/nginx/html/logs
      volumes:
      - name: sysmonitor-volume
        emptyDir: {}
