apiVersion: v1
kind: Service
metadata:
  name: monitoring-nginx
  namespace: monitoring
spec:
  selector:
    app: platforma-monitorizare
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort